# This file was generated by GoReleaser. DO NOT EDIT.
cask "kongvisor" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "2f979e8969f70a52822a934a4bb7d4d32c143f3ff3fed3a58af647a2d94bd30f"
      url "https://github.com/mchlumsky/kongvisor/releases/download/v#{version}/kongvisor_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "abbf56169586634b2fe93b8621827ca121511489ae89191d20ade510897eea68"
      url "https://github.com/mchlumsky/kongvisor/releases/download/v#{version}/kongvisor_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ddbad19e5f4d8cf1d0a277df2bbbf613199943d5ef03f1d1c416aea3dc2e5e25"
      url "https://github.com/mchlumsky/kongvisor/releases/download/v#{version}/kongvisor_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4b377e229a9409c8230b5467349d91d715255d5a4d5a3172012d79bf1605ffeb"
      url "https://github.com/mchlumsky/kongvisor/releases/download/v#{version}/kongvisor_Linux_arm64.tar.gz"
    end
  end

  name "kongvisor"
  desc "TUI for Kong Gateway Admin API"
  homepage "https://github.com/mchlumsky/kongvisor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kongvisor"

  # No zap stanza required

end
