# This file was generated by GoReleaser. DO NOT EDIT.
cask "kongvisor" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "2e6452aaa46012e2cf03e7cf97cae814a353d544112bccce7c303a85fb23aa7b"
      url "https://github.com/mchlumsky/kongvisor/releases/download/v#{version}/kongvisor_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d7ac67752286fdee63d1c6b94f31f17bac670c829ef25c57b0f097f1ac8e186e"
      url "https://github.com/mchlumsky/kongvisor/releases/download/v#{version}/kongvisor_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a695e0986d584235e6f66875aebb7e6e254166b9a900c05ae7b67ab829808142"
      url "https://github.com/mchlumsky/kongvisor/releases/download/v#{version}/kongvisor_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "29b98d69cb1110a47abdc278a4483e601f66df93080eb809d275b153327f5580"
      url "https://github.com/mchlumsky/kongvisor/releases/download/v#{version}/kongvisor_Linux_x86_64.tar.gz"
    end
  end

  name "kongvisor"
  desc "TUI for Kong Gateway Admin API"
  homepage "https://github.com/mchlumsky/kongvisor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kongvisor"

  # No zap stanza required
end
