# This file was generated by GoReleaser. DO NOT EDIT.
cask "mracek" do
  name "mracek"
  desc "Manage your OpenStack configuration files via CLI."
  homepage "https://github.com/mchlumsky/mracek"
  version "0.6.155"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mracek"
  bash_completion "completions/mracek.bash"
  zsh_completion "completions/mracek.zsh"
  fish_completion "completions/mracek.fish"

  on_macos do
    on_intel do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Darwin_x86_64.tar.gz"
      sha256 "ed457cf964e865935a2837964211478b9e26e8d52fce221df0b7cd266cb34b2a"
    end
    on_arm do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Darwin_arm64.tar.gz"
      sha256 "2ea82f6268b2ab1a50337a9db191aa69984965935bfcebdc3e1653da2a04202e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Linux_x86_64.tar.gz"
      sha256 "1f4d76c01c4c6ad189a4166ce55c39d421a8b481d98e12804cc9eb3ced329515"
    end
    on_arm do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Linux_arm64.tar.gz"
      sha256 "294be7f6a22df9b909c5aebee94a27255c441af3288eb34bba50bba21dfb912d"
    end
  end

  # No zap stanza required
end
