# This file was generated by GoReleaser. DO NOT EDIT.
cask "mracek" do
  name "mracek"
  desc "Manage your OpenStack configuration files via CLI."
  homepage "https://github.com/mchlumsky/mracek"
  version "0.6.149"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mracek"
  bash_completion "completions/mracek.bash"
  zsh_completion "completions/mracek.zsh"
  fish_completion "completions/mracek.fish"

  on_macos do
    on_intel do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Darwin_x86_64.tar.gz"
      sha256 "4d87b3ecae37c38adb570e1b85833ba253af0cc83fbf766d357201188eb025f2"
    end
    on_arm do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Darwin_arm64.tar.gz"
      sha256 "3c9429d4943c80df72c009df6e27badb6424c5ddd70430a996d69f1ca4fc4808"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Linux_x86_64.tar.gz"
      sha256 "fbf96ab111692b601f0a76274b38f38ca417fb30426607934aad4c256c7beea8"
    end
    on_arm do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Linux_arm64.tar.gz"
      sha256 "aa3394a8c37bb7902dcf97a7ad351573bb6a6dcb18a2d3fdccd20e96927d6d84"
    end
  end

  # No zap stanza required
end
