# This file was generated by GoReleaser. DO NOT EDIT.
cask "mracek" do
  name "mracek"
  desc "Manage your OpenStack configuration files via CLI."
  homepage "https://github.com/mchlumsky/mracek"
  version "0.6.153"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mracek"
  bash_completion "completions/mracek.bash"
  zsh_completion "completions/mracek.zsh"
  fish_completion "completions/mracek.fish"

  on_macos do
    on_intel do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Darwin_x86_64.tar.gz"
      sha256 "98318312123166dc97d2cf798dde25be5caf9b27dfa86b1d54d673383744dccf"
    end
    on_arm do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Darwin_arm64.tar.gz"
      sha256 "55b7aa13ec1dc3fb70cf146ee3e43de45548ba7bf6ff89a58dcc598acdedba09"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Linux_x86_64.tar.gz"
      sha256 "f011eab9f057d36c200175a16aa2bba297207793fbed533fc7d223b45537ad4e"
    end
    on_arm do
      url "https://github.com/mchlumsky/mracek/releases/download/v#{version}/mracek_Linux_arm64.tar.gz"
      sha256 "b3c9dee1d8dc847864f4348fc263555a5ba85942f640b235fc9bfc756fca5126"
    end
  end

  # No zap stanza required
end
